/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/authentication/hasauth/hasauth.directive';
import * as i1 from '@angular/core';
import * as i2 from '../../../../../src/app/authentication/authentication.store';
import * as i3 from '@angular/router';
import * as i4 from '@angular/forms';
export function HasAuthDirectiveNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.HasAuthDirective,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.ElementRef}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.AuthenticationStore}}},{isAttribute:false,
          isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.Renderer}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i3.ActivatedRoute}}},{isAttribute:false,isHost:false,
          isSelf:true,isSkipSelf:false,isOptional:true,token:{identifier:{reference:i4.NgControl}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i1.NgZone}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.ApplicationRef}}}],
      lifecycleHooks:[1,2]},isComponent:false,selector:'input:not([as4-no-auth]), select:not([as4-no-auth]), [as4-auth][disabled], [as4-auth]',
      exportAs:'auth',inputs:{required:'required',disabled:'as4-auth',formControlName:'formControlName'},
      outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:(null as any),template:(null as any),
      componentViewType:(null as any),rendererType:(null as any),componentFactory:(null as any)}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2F1dGhlbnRpY2F0aW9uL2hhc2F1dGgvaGFzYXV0aC5kaXJlY3RpdmUubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2F1dGhlbnRpY2F0aW9uL2hhc2F1dGgvaGFzYXV0aC5kaXJlY3RpdmUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
