/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../src/app/settings/base.component';
import * as i1 from '../../../../src/app/settings/settings.service';
import * as i2 from '@angular/forms';
import * as i3 from '../../../../src/app/settings/runtime.store';
import * as i4 from '../../../../src/app/common/dialog.service';
import * as i5 from './base.component.ngfactory';
export function BaseSettingsComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.BaseSettingsComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.SettingsService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.FormBuilder}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.RuntimeStore}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i4.DialogService}}}],lifecycleHooks:([] as any[])},
      isComponent:true,selector:'as4-base-settings',exportAs:(null as any),inputs:{settings:'settings'},
      outputs:{isDirty:'isDirty'},hostListeners:{},hostProperties:{},hostAttributes:{},
      providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{ngContentSelectors:([] as any[]),
          encapsulation:2},componentViewType:i5.View_BaseSettingsComponent_0,rendererType:i5.RenderType_BaseSettingsComponent,
      componentFactory:i5.BaseSettingsComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL3NldHRpbmdzL2Jhc2UuY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0Rldi9jb2RpdC52aXN1YWxzdHVkaW8uY29tL0FTNC5ORVQvc291cmNlL0ZlL0V1LkVEZWxpdmVyeS5BUzQuRmUvdWkvc3JjL2FwcC9zZXR0aW5ncy9iYXNlLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
