/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/settings/agent/agent.component';
import * as i1 from '../../../../../src/app/settings/settings.store';
import * as i2 from '../../../../../src/app/settings/runtime.store';
import * as i3 from '../../../../../src/app/settings/settings.service';
import * as i4 from '@angular/router';
import * as i5 from '../../../../../src/app/common/dialog.service';
import * as i6 from '../../../../../src/app/common/modal/modal.service';
import * as i7 from '../../../../../src/app/common/form.service';
import * as i8 from '@angular/core';
import * as i9 from './agent.component.ngfactory';
export function AgentSettingsComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.AgentSettingsComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.SettingsStore}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.RuntimeStore}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.SettingsService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i4.ActivatedRoute}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.DialogService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i6.ModalService}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i7.FormBuilderExtended}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i8.ChangeDetectorRef}}}],lifecycleHooks:[0,
      1]},isComponent:true,selector:'as4-agent-settings',exportAs:(null as any),inputs:{title:'title',
      agent:'agent',beType:'beType'},outputs:{},hostListeners:{},hostProperties:{},
      hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),
      viewQueries:([] as any[]),entryComponents:([] as any[]),changeDetection:0,template:{ngContentSelectors:([] as any[]),
          encapsulation:2},componentViewType:i9.View_AgentSettingsComponent_0,rendererType:i9.RenderType_AgentSettingsComponent,
      componentFactory:i9.AgentSettingsComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL3NldHRpbmdzL2FnZW50L2FnZW50LmNvbXBvbmVudC5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9EZXYvY29kaXQudmlzdWFsc3R1ZGlvLmNvbS9BUzQuTkVUL3NvdXJjZS9GZS9FdS5FRGVsaXZlcnkuQVM0LkZlL3VpL3NyYy9hcHAvc2V0dGluZ3MvYWdlbnQvYWdlbnQuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
