/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/pmodes/method/method.component';
import * as i1 from '@angular/forms';
import * as i2 from '../../../../../src/app/common/dialog.service';
import * as i3 from './method.component.ngfactory';
export function MethodComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.MethodComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.FormBuilder}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.DialogService}}}],lifecycleHooks:([] as any[])},
      isComponent:true,selector:'as4-method',exportAs:(null as any),inputs:{group:'group',
          types:'types',isDisabled:'isDisabled',label:'label',runtime:'runtime'},outputs:{},
      hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:0,template:{ngContentSelectors:([] as any[]),
          encapsulation:2},componentViewType:i3.View_MethodComponent_0,rendererType:i3.RenderType_MethodComponent,
      componentFactory:i3.MethodComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL3Btb2Rlcy9tZXRob2QvbWV0aG9kLmNvbXBvbmVudC5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9EZXYvY29kaXQudmlzdWFsc3R1ZGlvLmNvbS9BUzQuTkVUL3NvdXJjZS9GZS9FdS5FRGVsaXZlcnkuQVM0LkZlL3VpL3NyYy9hcHAvcG1vZGVzL21ldGhvZC9tZXRob2QuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
