/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../src/app/common/focus.directive';
import * as i1 from '@angular/core';
export function FocusDirectiveNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.FocusDirective,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.ElementRef}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:true,isOptional:true,
          token:{identifier:{reference:i0.FocusDirective}}}],lifecycleHooks:[2]},isComponent:false,
      selector:'[focus]',exportAs:(null as any),inputs:{onlyWhenNoText:'onlyWhenNoText',
          disabled:'focus-disabled'},outputs:{},hostListeners:{},hostProperties:{},
      hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),queries:[{selectors:[{identifier:{reference:i0.FocusDirective}}],
          first:false,descendants:false,propertyName:'tabIndexes',read:(null as any)}],
      viewQueries:([] as any[]),entryComponents:([] as any[]),changeDetection:(null as any),
      template:(null as any),componentViewType:(null as any),rendererType:(null as any),
      componentFactory:(null as any)}];
}
export function TabIndexDirectiveNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.TabIndexDirective,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.ElementRef}}}],
      lifecycleHooks:([] as any[])},isComponent:false,selector:'[tabIndex]',exportAs:(null as any),
      inputs:{tabIndex:'tabIndex'},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},
      providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:(null as any),template:(null as any),
      componentViewType:(null as any),rendererType:(null as any),componentFactory:(null as any)}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2NvbW1vbi9mb2N1cy5kaXJlY3RpdmUubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2NvbW1vbi9mb2N1cy5kaXJlY3RpdmUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
