/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../src/app/common/getitemtypeproperty.pipe';
export function GetItemTypePropertyPipeNgSummary():any[] {
  return [{summaryKind:0,type:{reference:i0.GetItemTypePropertyPipe,diDeps:([] as any[]),
      lifecycleHooks:([] as any[])},name:'getitemtypeproperty',pure:true}];
}
export function GetTypePipeNgSummary():any[] {
  return [{summaryKind:0,type:{reference:i0.GetTypePipe,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
      name:'gettype',pure:true}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2NvbW1vbi9nZXRpdGVtdHlwZXByb3BlcnR5LnBpcGUubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2NvbW1vbi9nZXRpdGVtdHlwZXByb3BlcnR5LnBpcGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
