/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../src/app/common/runtimetooltip.directive';
export function RuntimetoolTipDirectiveNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.RuntimetoolTipDirective,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:true,isOptional:true,token:{identifier:{reference:i0.RuntimetoolTipDirective}}}],
      lifecycleHooks:([] as any[])},isComponent:false,selector:'[runtimeTooltip]',
      exportAs:(null as any),inputs:{runtimeTooltip:'runtimeTooltip'},outputs:{},hostListeners:{},
      hostProperties:{},hostAttributes:{},providers:([] as any[]),viewProviders:([] as any[]),
      queries:([] as any[]),viewQueries:([] as any[]),entryComponents:([] as any[]),
      changeDetection:(null as any),template:(null as any),componentViewType:(null as any),
      rendererType:(null as any),componentFactory:(null as any)}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2NvbW1vbi9ydW50aW1ldG9vbHRpcC5kaXJlY3RpdmUubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2NvbW1vbi9ydW50aW1ldG9vbHRpcC5kaXJlY3RpdmUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
