/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/monitor/errormessage/errormessage.component';
import * as i1 from '../../../../../src/app/monitor/exception/exception.store';
import * as i2 from '../../../../../src/app/monitor/message/message.service';
import * as i3 from './errormessage.component.ngfactory';
export function ErrorMessageComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.ErrorMessageComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.ExceptionStore}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.MessageService}}}],lifecycleHooks:[0]},isComponent:true,
      selector:'as4-error-message',exportAs:(null as any),inputs:{message:'message',
          direction:'direction'},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},
      providers:([] as any[]),viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{ngContentSelectors:([] as any[]),
          encapsulation:2},componentViewType:i3.View_ErrorMessageComponent_0,rendererType:i3.RenderType_ErrorMessageComponent,
      componentFactory:i3.ErrorMessageComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvZXJyb3JtZXNzYWdlL2Vycm9ybWVzc2FnZS5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvZXJyb3JtZXNzYWdlL2Vycm9ybWVzc2FnZS5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
