/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../src/app/monitor/downloadmessagebody/downloadmessagebody.component';
import * as i2 from '../../../../../src/app/common/tooltip.directive';
import * as i3 from '../../../../../src/app/monitor/message/message.service';
import * as i4 from '../../../../../src/app/monitor/exception/exception.service';
const styles_DownloadMessageBodyComponent:any[] = ([] as any[]);
export const RenderType_DownloadMessageBodyComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_DownloadMessageBodyComponent,data:{}});
export function View_DownloadMessageBodyComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        \n'])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),1,'i',[['class','fa fa-download clickable']],(null as any),
      [[(null as any),'click'],['document','keydown']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.DownloadMessageBodyComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>i0.ɵnov(_v,2).onClick($event)) !== false);
          ad = (pd_0 && ad);
        }
        if (('document:keydown' === en)) {
          const pd_1:any = ((<any>i0.ɵnov(_v,2).onKeyDown()) !== false);
          ad = (pd_1 && ad);
        }
        if (('click' === en)) {
          const pd_2:any = ((<any>_co.download()) !== false);
          ad = (pd_2 && ad);
        }
        return ad;
      },(null as any),(null as any))),i0.ɵdid(2,212992,(null as any),0,i2.TooltipDirective,
      [i0.Renderer,i0.ElementRef,[3,i2.TooltipDirective]],{input:[0,'input']},(null as any)),
      (_l()(),i0.ɵted(-1,(null as any),['\n    ']))],(_ck,_v) => {
    var _co:i1.DownloadMessageBodyComponent = _v.component;
    const currVal_0:any = i0.ɵinlineInterpolate(1,'',_co.tooltip,'');
    _ck(_v,2,0,currVal_0);
  },(null as any));
}
export function View_DownloadMessageBodyComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'as4-downloadmessagebody',
      ([] as any[]),(null as any),(null as any),(null as any),View_DownloadMessageBodyComponent_0,
      RenderType_DownloadMessageBodyComponent)),i0.ɵdid(1,49152,(null as any),0,i1.DownloadMessageBodyComponent,
      [i3.MessageService,i4.ExceptionService],(null as any),(null as any))],(null as any),
      (null as any));
}
export const DownloadMessageBodyComponentNgFactory:i0.ComponentFactory<i1.DownloadMessageBodyComponent> = i0.ɵccf('as4-downloadmessagebody',
    i1.DownloadMessageBodyComponent,View_DownloadMessageBodyComponent_Host_0,{direction:'direction',
        id:'id',name:'name',type:'type',tooltip:'tooltip'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvZG93bmxvYWRtZXNzYWdlYm9keS9kb3dubG9hZG1lc3NhZ2Vib2R5LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9EZXYvY29kaXQudmlzdWFsc3R1ZGlvLmNvbS9BUzQuTkVUL3NvdXJjZS9GZS9FdS5FRGVsaXZlcnkuQVM0LkZlL3VpL3NyYy9hcHAvbW9uaXRvci9kb3dubG9hZG1lc3NhZ2Vib2R5L2Rvd25sb2FkbWVzc2FnZWJvZHkuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvZG93bmxvYWRtZXNzYWdlYm9keS9kb3dubG9hZG1lc3NhZ2Vib2R5LmNvbXBvbmVudC50cy5Eb3dubG9hZE1lc3NhZ2VCb2R5Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9EZXYvY29kaXQudmlzdWFsc3R1ZGlvLmNvbS9BUzQuTkVUL3NvdXJjZS9GZS9FdS5FRGVsaXZlcnkuQVM0LkZlL3VpL3NyYy9hcHAvbW9uaXRvci9kb3dubG9hZG1lc3NhZ2Vib2R5L2Rvd25sb2FkbWVzc2FnZWJvZHkuY29tcG9uZW50LnRzLkRvd25sb2FkTWVzc2FnZUJvZHlDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgXG48aSBjbGFzcz1cImZhIGZhLWRvd25sb2FkIGNsaWNrYWJsZVwiIChjbGljayk9XCJkb3dubG9hZCgpXCIgYXM0LXRvb2x0aXA9XCJ7e3Rvb2x0aXB9fVwiPjwvaT5cbiAgICAiLCI8YXM0LWRvd25sb2FkbWVzc2FnZWJvZHk+PC9hczQtZG93bmxvYWRtZXNzYWdlYm9keT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQSxvREFFQTtNQUFBO01BQUE7UUFBQTtRQUFBO1FBQUE7VUFBQTtVQUFBO1FBQUE7UUFBQTtVQUFBO1VBQUE7UUFBQTtRQUFvQztVQUFBO1VBQUE7UUFBQTtRQUFwQztNQUFBLHVDQUFBO01BQUE7TUFBdUY7O0lBQTlCO0lBQXpELFdBQXlELFNBQXpEOzs7O29CQ0ZBO01BQUE7NkNBQUEsVUFBQTtNQUFBOzs7OzsifQ==
