/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/common/select2/select2.component';
import * as i1 from '@angular/forms';
import * as i2 from './select2.component.ngfactory';
export function Select2ComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.Select2Component,diDeps:([] as any[]),
      lifecycleHooks:[1,6]},isComponent:true,selector:'as4-select2',exportAs:(null as any),
      inputs:{data:'data',open:'open'},outputs:{change:'change'},hostListeners:{},
      hostProperties:{},hostAttributes:{},providers:[{token:{identifier:{reference:i1.NG_VALUE_ACCESSOR}},
          useClass:(null as any),useValue:(undefined as any),useFactory:(null as any),
          useExisting:{identifier:{reference:i0.Select2Component}},deps:(undefined as any),
          multi:true}],viewProviders:([] as any[]),queries:([] as any[]),viewQueries:[{selectors:[{value:'select'}],
          first:true,descendants:true,propertyName:'_select',read:(null as any)}],
      entryComponents:([] as any[]),changeDetection:0,template:{ngContentSelectors:([] as any[]),
          encapsulation:2},componentViewType:i2.View_Select2Component_0,rendererType:i2.RenderType_Select2Component,
      componentFactory:i2.Select2ComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2NvbW1vbi9zZWxlY3QyL3NlbGVjdDIuY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0Rldi9jb2RpdC52aXN1YWxzdHVkaW8uY29tL0FTNC5ORVQvc291cmNlL0ZlL0V1LkVEZWxpdmVyeS5BUzQuRmUvdWkvc3JjL2FwcC9jb21tb24vc2VsZWN0Mi9zZWxlY3QyLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
