/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/monitor/relatedmessages/relatedmessages.component';
import * as i1 from '../../../../../src/app/monitor/service.token';
import * as i2 from '../../../../../src/app/monitor/message/message.store';
import * as i3 from '../../../../../src/app/monitor/message/message.service';
import * as i4 from 'angular2-jwt/angular2-jwt';
import * as i5 from '../../../../../src/app/common/spinner/customhttp';
import * as i6 from '../../../../../src/app/monitor/exception/exception.service';
import * as i7 from './relatedmessages.component.ngfactory';
export function RelatedMessagesComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.RelatedMessagesComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.MESSAGESERVICETOKEN}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.MessageStore}}}],lifecycleHooks:[0]},isComponent:true,
      selector:'as4-related-messages',exportAs:(null as any),inputs:{messageId:'messageId',
          direction:'direction'},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},
      providers:[{token:{identifier:{reference:i1.MESSAGESERVICETOKEN}},useClass:{reference:i3.MessageService,
          diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i4.AuthHttp}}},{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.CustomAuthNoSpinnerHttp}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i2.MessageStore}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i6.ExceptionService}}}],
          lifecycleHooks:([] as any[])},useValue:(undefined as any),useFactory:(null as any),
          useExisting:(undefined as any),deps:[{isAttribute:false,isHost:false,isSelf:false,
              isSkipSelf:false,isOptional:false,token:{identifier:{reference:i4.AuthHttp}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i5.CustomAuthNoSpinnerHttp}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i2.MessageStore}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i6.ExceptionService}}}],multi:false},
          {token:{identifier:{reference:i2.MessageStore,diDeps:([] as any[]),lifecycleHooks:([] as any[])}},
              useClass:{reference:i2.MessageStore,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
              useValue:(undefined as any),useFactory:(null as any),useExisting:(undefined as any),
              deps:([] as any[]),multi:false}],viewProviders:([] as any[]),queries:([] as any[]),
      viewQueries:([] as any[]),entryComponents:([] as any[]),changeDetection:1,template:{ngContentSelectors:([] as any[]),
          encapsulation:2},componentViewType:i7.View_RelatedMessagesComponent_0,rendererType:i7.RenderType_RelatedMessagesComponent,
      componentFactory:i7.RelatedMessagesComponentNgFactory},{summaryKind:3,type:{reference:i3.MessageService,
      diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i4.AuthHttp}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.CustomAuthNoSpinnerHttp}}},
          {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i2.MessageStore}}},{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i6.ExceptionService}}}],
      lifecycleHooks:([] as any[])}},{summaryKind:3,type:{reference:i2.MessageStore,
      diDeps:([] as any[]),lifecycleHooks:([] as any[])}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvcmVsYXRlZG1lc3NhZ2VzL3JlbGF0ZWRtZXNzYWdlcy5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvcmVsYXRlZG1lc3NhZ2VzL3JlbGF0ZWRtZXNzYWdlcy5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
