/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../src/app/app.component';
import * as i1 from '../../../src/app/app.service';
import * as i2 from '../../../src/app/authentication/authentication.store';
import * as i3 from '../../../src/app/settings/runtime.service';
import * as i4 from '../../../src/app/common/modal/modal.service';
import * as i5 from '../../../src/app/common/dialog.service';
import * as i6 from '../../../src/app/pmodes/sendingpmode.service';
import * as i7 from '../../../src/app/pmodes/receivingpmode.service';
import * as i8 from '../../../src/app/settings/settings.service';
import * as i9 from '@angular/core';
import * as i10 from './app.component.ngfactory';
export function AppComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.AppComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.AppState}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.AuthenticationStore}}},{isAttribute:false,
          isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.RuntimeService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i4.ModalService}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.DialogService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i6.SendingPmodeService}}},{isAttribute:false,
          isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i7.ReceivingPmodeService}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i8.SettingsService}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i9.ViewContainerRef}}}],
      lifecycleHooks:[6]},isComponent:true,selector:'as4-app',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:[{selectors:[{value:'modal'}],
          first:true,descendants:true,propertyName:'modal',read:(null as any)}],entryComponents:([] as any[]),
      changeDetection:1,template:{ngContentSelectors:([] as any[]),encapsulation:2},
      componentViewType:i10.View_AppComponent_0,rendererType:i10.RenderType_AppComponent,
      componentFactory:i10.AppComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2FwcC5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
