/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/no-content/no-content.component';
const styles_NoContentComponent:any[] = ([] as any[]);
export const RenderType_NoContentComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_NoContentComponent,data:{}});
export function View_NoContentComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),4,'div',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
      ['\n      '])),(_l()(),i0.ɵeld(3,0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['404: page missing'])),(_l()(),i0.ɵted(-1,(null as any),
      ['\n    '])),(_l()(),i0.ɵted(-1,(null as any),['\n  ']))],(null as any),(null as any));
}
export function View_NoContentComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'as4-no-content',
      ([] as any[]),(null as any),(null as any),(null as any),View_NoContentComponent_0,
      RenderType_NoContentComponent)),i0.ɵdid(1,49152,(null as any),0,i1.NoContentComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NoContentComponentNgFactory:i0.ComponentFactory<i1.NoContentComponent> = i0.ɵccf('as4-no-content',
    i1.NoContentComponent,View_NoContentComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL25vLWNvbnRlbnQvbm8tY29udGVudC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL25vLWNvbnRlbnQvbm8tY29udGVudC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9EZXYvY29kaXQudmlzdWFsc3R1ZGlvLmNvbS9BUzQuTkVUL3NvdXJjZS9GZS9FdS5FRGVsaXZlcnkuQVM0LkZlL3VpL3NyYy9hcHAvbm8tY29udGVudC9uby1jb250ZW50LmNvbXBvbmVudC50cy5Ob0NvbnRlbnRDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L0Rldi9jb2RpdC52aXN1YWxzdHVkaW8uY29tL0FTNC5ORVQvc291cmNlL0ZlL0V1LkVEZWxpdmVyeS5BUzQuRmUvdWkvc3JjL2FwcC9uby1jb250ZW50L25vLWNvbnRlbnQuY29tcG9uZW50LnRzLk5vQ29udGVudENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXY+XG4gICAgICA8aDE+NDA0OiBwYWdlIG1pc3Npbmc8L2gxPlxuICAgIDwvZGl2PlxuICAiLCI8YXM0LW5vLWNvbnRlbnQ+PC9hczQtbm8tY29udGVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQSw4Q0FDSTtNQUFBO01BQUEsNENBQUs7TUFBQSxlQUNIO01BQUEsd0VBQUk7YUFBQSwwQ0FBc0I7TUFBQSxhQUN0Qjs7O29CQ0hWO01BQUE7bUNBQUEsVUFBQTtNQUFBOzs7In0=
