/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/common/multiselect/multiselect.directive';
import * as i1 from '@angular/core';
import * as i2 from '@angular/forms';
export function MultiSelectDirectiveNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.MultiSelectDirective,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.ElementRef}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i1.Renderer}}}],lifecycleHooks:[0,1,4]},isComponent:false,
      selector:'[multiselect]',exportAs:(null as any),inputs:{multiple:'multiple',
          data:'data'},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},
      providers:[{token:{identifier:{reference:i2.NG_VALUE_ACCESSOR}},useClass:(null as any),
          useValue:(undefined as any),useFactory:(null as any),useExisting:{identifier:{reference:i0.MultiSelectDirective}},
          deps:(undefined as any),multi:true}],viewProviders:([] as any[]),queries:[{selectors:[{identifier:{reference:i0.OptionDirective}}],
          first:false,descendants:false,propertyName:'children',read:(null as any)}],
      viewQueries:([] as any[]),entryComponents:([] as any[]),changeDetection:(null as any),
      template:(null as any),componentViewType:(null as any),rendererType:(null as any),
      componentFactory:(null as any)}];
}
export function OptionDirectiveNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.OptionDirective,diDeps:([] as any[]),lifecycleHooks:([] as any[])},
      isComponent:false,selector:'option',exportAs:(null as any),inputs:{},outputs:{},
      hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:(null as any),template:(null as any),
      componentViewType:(null as any),rendererType:(null as any),componentFactory:(null as any)}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2NvbW1vbi9tdWx0aXNlbGVjdC9tdWx0aXNlbGVjdC5kaXJlY3RpdmUubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2NvbW1vbi9tdWx0aXNlbGVjdC9tdWx0aXNlbGVjdC5kaXJlY3RpdmUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
