/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/monitor/pager/pager.component';
import * as i1 from './pager.component.ngfactory';
export function PagerComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.PagerComponent,diDeps:([] as any[]),lifecycleHooks:[3]},
      isComponent:true,selector:'as4-pager, [as4-pager]',exportAs:(null as any),inputs:{pages:'pages',
          page:'page',total:'total',pageTotal:'pageTotal'},outputs:{onChangePage:'onChangePage'},
      hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:0,template:{ngContentSelectors:([] as any[]),
          encapsulation:0},componentViewType:i1.View_PagerComponent_0,rendererType:i1.RenderType_PagerComponent,
      componentFactory:i1.PagerComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvcGFnZXIvcGFnZXIuY29tcG9uZW50Lm5nc3VtbWFyeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0Rldi9jb2RpdC52aXN1YWxzdHVkaW8uY29tL0FTNC5ORVQvc291cmNlL0ZlL0V1LkVEZWxpdmVyeS5BUzQuRmUvdWkvc3JjL2FwcC9tb25pdG9yL3BhZ2VyL3BhZ2VyLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
