/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/common/sidebar/sidebar.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from '../../../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import10 from '@angular/core/src/linker/query_list';
import * as import11 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '@angular/core/src/change_detection/change_detection_util';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/router/src/router_state';
import * as import16 from '@angular/common/src/location/location_strategy';
import * as import17 from '@angular/router/src/directives/router_link';
import * as import18 from '@angular/router/src/directives/router_link_active';
import * as import19 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/common/src/directives/ng_if';
import * as import22 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import23 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import24 from '@angular/common/src/directives/ng_for';
export class Wrapper_SidebarComponent {
  /*private*/ _eventHandler:Function;
  context:import0.SidebarComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.SidebarComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_SidebarComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_SidebarComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.SidebarComponent>;
  _SidebarComponent_0_3:Wrapper_SidebarComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SidebarComponent_Host0,renderType_SidebarComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'as4-sidebar',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_SidebarComponent0(this.viewUtils,this,0,this._el_0);
    this._SidebarComponent_0_3 = new Wrapper_SidebarComponent(this.injectorGet(import8.Router,this.parentIndex));
    this.compView_0.create(this._SidebarComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._SidebarComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SidebarComponent) && (0 === requestNodeIndex))) { return this._SidebarComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._SidebarComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const SidebarComponentNgFactory:import7.ComponentFactory<import0.SidebarComponent> = new import7.ComponentFactory<import0.SidebarComponent>('as4-sidebar',View_SidebarComponent_Host0,import0.SidebarComponent);
const styles_SidebarComponent:any[] = ([] as any[]);
class View_SidebarComponent2 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkActive_0_3:import9.Wrapper_RouterLinkActive;
  _query_RouterLink_0_0:import10.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import10.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _RouterLinkWithHref_2_3:import11.Wrapper_RouterLinkWithHref;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SidebarComponent2,renderType_SidebarComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_10 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray2(2,'routerLinkActive','active'),(null as any));
    this._RouterLinkActive_0_3 = new import9.Wrapper_RouterLinkActive(this.parentView.parentView.parentView.injectorGet(import8.Router,this.parentView.parentView.parentIndex),new import14.ElementRef(this._el_0),this.renderer,this.parentView.parentView.ref);
    this._query_RouterLink_0_0 = new import10.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import10.QueryList<any>();
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_2_3 = new import11.Wrapper_RouterLinkWithHref(this.parentView.parentView.parentView.injectorGet(import8.Router,this.parentView.parentView.parentIndex),this.parentView.parentView.parentView.injectorGet(import15.ActivatedRoute,this.parentView.parentView.parentIndex),this.parentView.parentView.parentView.injectorGet(import16.LocationStrategy,this.parentView.parentView.parentIndex));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_2,'i',new import3.InlineArray2(2,'class','fa fa-book'),(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.RouterLinkWithHref) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._RouterLinkWithHref_2_3.context; }
    if (((token === import18.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._RouterLinkActive_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'active';
    this._RouterLinkActive_0_3.check_routerLinkActive(currVal_0_0_0,throwOnChange,false);
    this._RouterLinkActive_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = import3.inlineInterpolate(1,'/',this.parentView.context.$implicit.path,'');
    this._RouterLinkWithHref_2_3.check_routerLink(currVal_2_0_0,throwOnChange,false);
    this._RouterLinkWithHref_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset(([] as any[]));
        this._RouterLinkActive_0_3.context.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
        this._query_RouterLinkWithHref_0_1.reset([this._RouterLinkWithHref_2_3.context]);
        this._RouterLinkActive_0_3.context.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_3.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_2_3.checkHost(this,this,this._el_2,throwOnChange);
    const currVal_10:any = import3.inlineInterpolate(1,'',this.parentView.context.$implicit.data.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_4,currVal_10);
      this._expr_10 = currVal_10;
    }
  }
  destroyInternal():void {
    this._RouterLinkWithHref_2_3.ngOnDestroy();
    this._RouterLinkActive_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_SidebarComponent7 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkActive_0_3:import9.Wrapper_RouterLinkActive;
  _query_RouterLink_0_0:import10.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import10.QueryList<any>;
  _el_1:any;
  _RouterLinkWithHref_1_3:import11.Wrapper_RouterLinkWithHref;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SidebarComponent7,renderType_SidebarComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_8 = import13.UNINITIALIZED;
    this._expr_9 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray2(2,'routerLinkActive','active'),(null as any));
    this._RouterLinkActive_0_3 = new import9.Wrapper_RouterLinkActive(this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.injectorGet(import8.Router,this.parentView.parentView.parentView.parentView.parentView.parentView.parentIndex),new import14.ElementRef(this._el_0),this.renderer,this.parentView.parentView.parentView.parentView.parentView.parentView.ref);
    this._query_RouterLink_0_0 = new import10.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import10.QueryList<any>();
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_1_3 = new import11.Wrapper_RouterLinkWithHref(this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.injectorGet(import8.Router,this.parentView.parentView.parentView.parentView.parentView.parentView.parentIndex),this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.injectorGet(import15.ActivatedRoute,this.parentView.parentView.parentView.parentView.parentView.parentView.parentIndex),this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.injectorGet(import16.LocationStrategy,this.parentView.parentView.parentView.parentView.parentView.parentView.parentIndex));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_1,'i',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLinkWithHref_1_3.context; }
    if (((token === import18.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLinkActive_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'active';
    this._RouterLinkActive_0_3.check_routerLinkActive(currVal_0_0_0,throwOnChange,false);
    this._RouterLinkActive_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_1_0_0:any = import3.inlineInterpolate(2,'/',this.parentView.parentView.parentView.parentView.parentView.context.$implicit.path,'/',this.parentView.parentView.context.$implicit.path,'');
    this._RouterLinkWithHref_1_3.check_routerLink(currVal_1_0_0,throwOnChange,false);
    this._RouterLinkWithHref_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset(([] as any[]));
        this._RouterLinkActive_0_3.context.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
        this._query_RouterLinkWithHref_0_1.reset([this._RouterLinkWithHref_1_3.context]);
        this._RouterLinkActive_0_3.context.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_3.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_1_3.checkHost(this,this,this._el_1,throwOnChange);
    const currVal_8:any = import3.inlineInterpolate(1,'fa ',(this.parentView.parentView.context.$implicit.data.icon? this.parentView.parentView.context.$implicit.data.icon: 'fa-adjust'),'');
    if (import3.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_2,'className',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.$implicit.data.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_3,currVal_9);
      this._expr_9 = currVal_9;
    }
  }
  dirtyParentQueriesInternal():void {
    (<View_SidebarComponent3>this.parentView.parentView.parentView.parentView)._query_RouterLinkWithHref_0_1.setDirty();
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
    this._RouterLinkActive_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_1_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_SidebarComponent10 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkActive_0_3:import9.Wrapper_RouterLinkActive;
  _query_RouterLink_0_0:import10.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import10.QueryList<any>;
  _el_1:any;
  _RouterLinkWithHref_1_3:import11.Wrapper_RouterLinkWithHref;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SidebarComponent10,renderType_SidebarComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_8 = import13.UNINITIALIZED;
    this._expr_9 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray2(2,'routerLinkActive','active'),(null as any));
    this._RouterLinkActive_0_3 = new import9.Wrapper_RouterLinkActive(this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.injectorGet(import8.Router,this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentIndex),new import14.ElementRef(this._el_0),this.renderer,this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.ref);
    this._query_RouterLink_0_0 = new import10.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import10.QueryList<any>();
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_1_3 = new import11.Wrapper_RouterLinkWithHref(this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.injectorGet(import8.Router,this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentIndex),this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.injectorGet(import15.ActivatedRoute,this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentIndex),this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.injectorGet(import16.LocationStrategy,this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentView.parentIndex));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_1,'i',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLinkWithHref_1_3.context; }
    if (((token === import18.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLinkActive_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'active';
    this._RouterLinkActive_0_3.check_routerLinkActive(currVal_0_0_0,throwOnChange,false);
    this._RouterLinkActive_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_1_0_0:any = import3.inlineInterpolate(3,'/',this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.context.$implicit.path,'/',this.parentView.parentView.parentView.parentView.context.$implicit.path,'/',this.parentView.context.$implicit.path,'');
    this._RouterLinkWithHref_1_3.check_routerLink(currVal_1_0_0,throwOnChange,false);
    this._RouterLinkWithHref_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset(([] as any[]));
        this._RouterLinkActive_0_3.context.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
        this._query_RouterLinkWithHref_0_1.reset([this._RouterLinkWithHref_1_3.context]);
        this._RouterLinkActive_0_3.context.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_3.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_1_3.checkHost(this,this,this._el_1,throwOnChange);
    const currVal_8:any = import3.inlineInterpolate(1,'fa ',(this.parentView.context.$implicit.data.icon? this.parentView.context.$implicit.data.icon: 'fa-adjust'),'');
    if (import3.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_2,'className',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import3.inlineInterpolate(1,'',this.parentView.context.$implicit.data.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_3,currVal_9);
      this._expr_9 = currVal_9;
    }
  }
  dirtyParentQueriesInternal():void {
    (<View_SidebarComponent8>this.parentView.parentView)._query_RouterLinkWithHref_0_1.setDirty();
    (<View_SidebarComponent3>this.parentView.parentView.parentView.parentView.parentView.parentView)._query_RouterLinkWithHref_0_1.setDirty();
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.ngOnDestroy();
    this._RouterLinkActive_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_1_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_SidebarComponent9 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import12.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import19.Wrapper_NgIf;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SidebarComponent9,renderType_SidebarComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._text_1 = this.renderer.createText((null as any),'\n                                            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_2 = new import12.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import20.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import19.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText((null as any),'\n                                        ',(null as any));
    this.init(this._text_3,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import21.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = (this.context.$implicit.data && (this.context.$implicit.data.title !== (undefined as any)));
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
    cb(this._text_1,ctx);
    cb(this._vc_2.nativeElement,ctx);
    this._vc_2.visitNestedViewRootNodes(cb,ctx);
    cb(this._text_3,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_SidebarComponent10(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_SidebarComponent8 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkActive_0_3:import9.Wrapper_RouterLinkActive;
  _query_RouterLink_0_0:import10.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import10.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _vc_16:import12.ViewContainer;
  _TemplateRef_16_5:any;
  _NgFor_16_6:import22.Wrapper_NgFor;
  _text_17:any;
  _text_18:any;
  /*private*/ _expr_25:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SidebarComponent8,renderType_SidebarComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_25 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray2(2,'routerLinkActive','active'),(null as any));
    this._RouterLinkActive_0_3 = new import9.Wrapper_RouterLinkActive(this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.injectorGet(import8.Router,this.parentView.parentView.parentView.parentView.parentView.parentView.parentIndex),new import14.ElementRef(this._el_0),this.renderer,this.parentView.parentView.parentView.parentView.parentView.parentView.ref);
    this._query_RouterLink_0_0 = new import10.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import10.QueryList<any>();
    this._text_1 = this.renderer.createText(this._el_0,'\n                                    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'i',new import3.InlineArray2(2,'class','fa fa-table'),(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_2,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_2,'\n                                        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_2,'span',new import3.InlineArray2(2,'class','pull-right-container'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                                            ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'i',new import3.InlineArray2(2,'class','fa fa-angle-left pull-right'),(null as any));
    this._text_11 = this.renderer.createText(this._el_8,'\n                                        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n                                    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n                                    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_0,'ul',new import3.InlineArray2(2,'class','treeview-menu'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                                        ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._vc_16 = new import12.ViewContainer(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import20.TemplateRef_(this,16,this._anchor_16);
    this._NgFor_16_6 = new import22.Wrapper_NgFor(this._vc_16.vcRef,this._TemplateRef_16_5,this.parentView.parentView.parentView.parentView.parentView.parentView.parentView.injectorGet(import23.IterableDiffers,this.parentView.parentView.parentView.parentView.parentView.parentView.parentIndex),this.parentView.parentView.parentView.parentView.parentView.parentView.ref);
    this._text_17 = this.renderer.createText(this._el_14,'\n                                    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import24.NgFor) && (16 === requestNodeIndex))) { return this._NgFor_16_6.context; }
    if (((token === import18.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._RouterLinkActive_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'active';
    this._RouterLinkActive_0_3.check_routerLinkActive(currVal_0_0_0,throwOnChange,false);
    this._RouterLinkActive_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_16_0_0:any = this.parentView.parentView.context.$implicit.children;
    this._NgFor_16_6.check_ngForOf(currVal_16_0_0,throwOnChange,false);
    this._NgFor_16_6.ngDoCheck(this,this._anchor_16,throwOnChange);
    this._vc_16.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset(([] as any[]));
        this._RouterLinkActive_0_3.context.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
          this._query_RouterLinkWithHref_0_1.reset([this._vc_16.mapNestedViews(View_SidebarComponent9,(nestedView:View_SidebarComponent9):any => {
              return [nestedView._vc_2.mapNestedViews(View_SidebarComponent10,(nestedView:View_SidebarComponent10):any => {
                return [nestedView._RouterLinkWithHref_1_3.context];
            })];
        })]);
        this._RouterLinkActive_0_3.context.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_3.context.ngAfterContentInit(); }
    }
    const currVal_25:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.$implicit.data.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setText(this._text_6,currVal_25);
      this._expr_25 = currVal_25;
    }
  }
  destroyInternal():void {
    this._vc_16.destroyNestedViews();
    this._RouterLinkActive_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 16)) { return new View_SidebarComponent9(this.viewUtils,this,16,this._anchor_16,this._vc_16); }
    return (null as any);
  }
}
class View_SidebarComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import12.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import19.Wrapper_NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import12.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import19.Wrapper_NgIf;
  _text_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SidebarComponent6,renderType_SidebarComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'ul',new import3.InlineArray2(2,'class','treeview-menu'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import12.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import20.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import19.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_4 = new import12.ViewContainer(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import20.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import19.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import21.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import20.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import21.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = (((((this.parentView.context.$implicit.children == null)? (null as any): this.parentView.context.$implicit.children.length) === (null as any)) && this.parentView.context.$implicit.data) && (this.parentView.context.$implicit.data.title !== (undefined as any)));
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    const currVal_4_0_0:any = (((this.parentView.context.$implicit.children == null)? (null as any): this.parentView.context.$implicit.children.length) !== (null as any));
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_4.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_SidebarComponent7(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 4)) { return new View_SidebarComponent8(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
}
class View_SidebarComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import12.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import19.Wrapper_NgIf;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SidebarComponent5,renderType_SidebarComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._text_1 = this.renderer.createText((null as any),'\n                            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_2 = new import12.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import20.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import19.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText((null as any),'\n                        ',(null as any));
    this.init(this._text_3,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import21.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:boolean = !!this.context.$implicit.path;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
    cb(this._text_1,ctx);
    cb(this._vc_2.nativeElement,ctx);
    this._vc_2.visitNestedViewRootNodes(cb,ctx);
    cb(this._text_3,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_SidebarComponent6(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_SidebarComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import12.ViewContainer;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import22.Wrapper_NgFor;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SidebarComponent4,renderType_SidebarComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._text_1 = this.renderer.createText((null as any),'\n                        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_2 = new import12.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import20.TemplateRef_(this,2,this._anchor_2);
    this._NgFor_2_6 = new import22.Wrapper_NgFor(this._vc_2.vcRef,this._TemplateRef_2_5,this.parentView.parentView.parentView.parentView.injectorGet(import23.IterableDiffers,this.parentView.parentView.parentView.parentIndex),this.parentView.parentView.parentView.ref);
    this._text_3 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this.init(this._text_3,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import24.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.parentView.context.$implicit.children;
    this._NgFor_2_6.check_ngForOf(currVal_2_0_0,throwOnChange,false);
    this._NgFor_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
    cb(this._text_1,ctx);
    cb(this._vc_2.nativeElement,ctx);
    this._vc_2.visitNestedViewRootNodes(cb,ctx);
    cb(this._text_3,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_SidebarComponent5(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_SidebarComponent3 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkActive_0_3:import9.Wrapper_RouterLinkActive;
  _query_RouterLink_0_0:import10.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import10.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _vc_14:import12.ViewContainer;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import19.Wrapper_NgIf;
  _text_15:any;
  /*private*/ _expr_22:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SidebarComponent3,renderType_SidebarComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_22 = import13.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',new import3.InlineArray4(4,'class','treeview','routerLinkActive','active'),(null as any));
    this._RouterLinkActive_0_3 = new import9.Wrapper_RouterLinkActive(this.parentView.parentView.parentView.injectorGet(import8.Router,this.parentView.parentView.parentIndex),new import14.ElementRef(this._el_0),this.renderer,this.parentView.parentView.ref);
    this._query_RouterLink_0_0 = new import10.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import10.QueryList<any>();
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'i',new import3.InlineArray2(2,'class','fa fa-table'),(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_2,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_2,'\n                        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_2,'span',new import3.InlineArray2(2,'class','pull-right-container'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                            ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'i',new import3.InlineArray2(2,'class','fa fa-angle-left pull-right'),(null as any));
    this._text_11 = this.renderer.createText(this._el_8,'\n                        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_14 = new import12.ViewContainer(14,0,this,this._anchor_14);
    this._TemplateRef_14_5 = new import20.TemplateRef_(this,14,this._anchor_14);
    this._NgIf_14_6 = new import19.Wrapper_NgIf(this._vc_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._anchor_14,
      this._text_15
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import21.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6.context; }
    if (((token === import18.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._RouterLinkActive_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'active';
    this._RouterLinkActive_0_3.check_routerLinkActive(currVal_0_0_0,throwOnChange,false);
    this._RouterLinkActive_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_14_0_0:boolean = !!this.parentView.context.$implicit.children;
    this._NgIf_14_6.check_ngIf(currVal_14_0_0,throwOnChange,false);
    this._NgIf_14_6.ngDoCheck(this,this._anchor_14,throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset(([] as any[]));
        this._RouterLinkActive_0_3.context.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
          this._query_RouterLinkWithHref_0_1.reset([this._vc_14.mapNestedViews(View_SidebarComponent4,(nestedView:View_SidebarComponent4):any => {
              return [nestedView._vc_2.mapNestedViews(View_SidebarComponent5,(nestedView:View_SidebarComponent5):any => {
                  return [nestedView._vc_2.mapNestedViews(View_SidebarComponent6,(nestedView:View_SidebarComponent6):any => {
                    return [
                      nestedView._vc_2.mapNestedViews(View_SidebarComponent7,(nestedView:View_SidebarComponent7):any => {
                        return [nestedView._RouterLinkWithHref_1_3.context];
                      }),
                      nestedView._vc_4.mapNestedViews(View_SidebarComponent8,(nestedView:View_SidebarComponent8):any => {
                          return [nestedView._vc_16.mapNestedViews(View_SidebarComponent9,(nestedView:View_SidebarComponent9):any => {
                              return [nestedView._vc_2.mapNestedViews(View_SidebarComponent10,(nestedView:View_SidebarComponent10):any => {
                                return [nestedView._RouterLinkWithHref_1_3.context];
                            })];
                        })];
                      })
                    ]
                    ;
                })];
            })];
        })]);
        this._RouterLinkActive_0_3.context.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_3.context.ngAfterContentInit(); }
    }
    const currVal_22:any = import3.inlineInterpolate(1,'',this.parentView.context.$implicit.data.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setText(this._text_6,currVal_22);
      this._expr_22 = currVal_22;
    }
  }
  destroyInternal():void {
    this._vc_14.destroyNestedViews();
    this._RouterLinkActive_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 14)) { return new View_SidebarComponent4(this.viewUtils,this,14,this._anchor_14,this._vc_14); }
    return (null as any);
  }
}
class View_SidebarComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import12.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import19.Wrapper_NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import12.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import19.Wrapper_NgIf;
  _text_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_SidebarComponent1,renderType_SidebarComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._text_1 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_2 = new import12.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import20.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import19.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_4 = new import12.ViewContainer(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import20.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import19.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText((null as any),'\n            ',(null as any));
    this.init(this._text_5,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import21.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import20.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import21.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:boolean = !!!this.context.$implicit.children;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    const currVal_4_0_0:boolean = !!((this.context.$implicit && this.context.$implicit.children) && (this.context.$implicit.children.length > 0));
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_4.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
    cb(this._text_1,ctx);
    cb(this._vc_2.nativeElement,ctx);
    this._vc_2.visitNestedViewRootNodes(cb,ctx);
    cb(this._text_3,ctx);
    cb(this._vc_4.nativeElement,ctx);
    this._vc_4.visitNestedViewRootNodes(cb,ctx);
    cb(this._text_5,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_SidebarComponent2(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 4)) { return new View_SidebarComponent3(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
}
var renderType_SidebarComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_SidebarComponent,{});
export class View_SidebarComponent0 extends import1.AppView<import0.SidebarComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _vc_12:import12.ViewContainer;
  _TemplateRef_12_5:any;
  _NgFor_12_6:import22.Wrapper_NgFor;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SidebarComponent0,renderType_SidebarComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'aside',new import3.InlineArray2(2,'class','main-sidebar'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'section',new import3.InlineArray2(2,'class','sidebar'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','user-panel'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','pull-left image'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_2,'ul',new import3.InlineArray2(2,'class','sidebar-menu'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._vc_12 = new import12.ViewContainer(12,10,this,this._anchor_12);
    this._TemplateRef_12_5 = new import20.TemplateRef_(this,12,this._anchor_12);
    this._NgFor_12_6 = new import22.Wrapper_NgFor(this._vc_12.vcRef,this._TemplateRef_12_5,this.parentView.injectorGet(import23.IterableDiffers,this.parentIndex),this.ref);
    this._text_13 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import24.NgFor) && (12 === requestNodeIndex))) { return this._NgFor_12_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_12_0_0:any = this.context.routes;
    this._NgFor_12_6.check_ngForOf(currVal_12_0_0,throwOnChange,false);
    this._NgFor_12_6.ngDoCheck(this,this._anchor_12,throwOnChange);
    this._vc_12.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_12.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 12)) { return new View_SidebarComponent1(this.viewUtils,this,12,this._anchor_12,this._vc_12); }
    return (null as any);
  }
}