/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../../src/app/monitor/message/message.component';
import * as i1 from '../../../../../src/app/monitor/message/message.store';
import * as i2 from '../../../../../src/app/monitor/message/message.service';
import * as i3 from '@angular/forms';
import * as i4 from '../../../../../src/app/monitor/service.token';
import * as i5 from 'angular2-jwt/angular2-jwt';
import * as i6 from '../../../../../src/app/common/spinner/customhttp';
import * as i7 from '../../../../../src/app/monitor/exception/exception.service';
import * as i8 from './message.component.ngfactory';
export function MessageComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.MessageComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.MessageStore}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.MessageService}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i3.FormBuilder}}}],
      lifecycleHooks:[1]},isComponent:true,selector:'as4-messages',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:[{token:{identifier:{reference:i4.MESSAGESERVICETOKEN}},
          useClass:{reference:i2.MessageService,diDeps:[{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i5.AuthHttp}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i6.CustomAuthNoSpinnerHttp}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.MessageStore}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i7.ExceptionService}}}],lifecycleHooks:([] as any[])},
          useValue:(undefined as any),useFactory:(null as any),useExisting:(undefined as any),
          deps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i5.AuthHttp}}},{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i6.CustomAuthNoSpinnerHttp}}},
              {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
                  token:{identifier:{reference:i1.MessageStore}}},{isAttribute:false,
                  isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i7.ExceptionService}}}],
          multi:false}],viewProviders:([] as any[]),queries:([] as any[]),viewQueries:[{selectors:[{value:'filter'}],
          first:true,descendants:true,propertyName:'filter',read:(null as any)}],entryComponents:([] as any[]),
      changeDetection:0,template:{ngContentSelectors:([] as any[]),encapsulation:0},
      componentViewType:i8.View_MessageComponent_0,rendererType:i8.RenderType_MessageComponent,
      componentFactory:i8.MessageComponentNgFactory},{summaryKind:3,type:{reference:i2.MessageService,
      diDeps:[{isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i5.AuthHttp}}},{isAttribute:false,isHost:false,
          isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i6.CustomAuthNoSpinnerHttp}}},
          {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
              token:{identifier:{reference:i1.MessageStore}}},{isAttribute:false,isHost:false,
              isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i7.ExceptionService}}}],
      lifecycleHooks:([] as any[])}}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvbWVzc2FnZS9tZXNzYWdlLmNvbXBvbmVudC5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9EZXYvY29kaXQudmlzdWFsc3R1ZGlvLmNvbS9BUzQuTkVUL3NvdXJjZS9GZS9FdS5FRGVsaXZlcnkuQVM0LkZlL3VpL3NyYy9hcHAvbW9uaXRvci9tZXNzYWdlL21lc3NhZ2UuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
