/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/settings/receptionawarenessagent/receptionawarenessagent.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/forms/src/form_builder';
import * as import9 from '../../../../../src/app/settings/settings.store';
import * as import10 from '../../../../../src/app/settings/settings.service';
import * as import11 from '../../../../../src/app/settings/runtime.service';
import * as import12 from '../../../../../src/app/settings/runtime.store';
import * as import13 from '../../../../../src/app/common/dialog.service';
import * as import14 from '../../../../node_modules/@angular/forms/src/directives/select_control_value_accessor.ngfactory';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.ngfactory';
import * as import16 from '@angular/core/src/linker/view_container';
import * as import17 from '@angular/core/src/change_detection/change_detection_util';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import20 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import21 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import22 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import23 from '../../../../../src/app/common/box/box.component';
import * as import24 from '../../common/box/box.component.ngfactory';
import * as import25 from '../../../../../src/app/common/input/input.component';
import * as import26 from '../../common/input/input.component.ngfactory';
import * as import27 from '../../common/text.directive.ngfactory';
import * as import28 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import29 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import30 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_name.ngfactory';
import * as import31 from '../../common/selectdirective.ngfactory';
import * as import32 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import33 from '../../../../../src/app/settings/receiver.component';
import * as import34 from '../receiver.component.ngfactory';
import * as import35 from '../../../../../src/app/settings/step/step.component';
import * as import36 from '../step/step.component.ngfactory';
import * as import37 from '@angular/core/src/linker/template_ref';
import * as import38 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import39 from '../../../../../src/app/common/text.directive';
import * as import40 from '@angular/forms/src/directives/default_value_accessor';
import * as import41 from '@angular/forms/src/directives/control_value_accessor';
import * as import42 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import43 from '@angular/forms/src/directives/ng_control';
import * as import44 from '@angular/forms/src/directives/ng_control_status';
import * as import45 from '@angular/common/src/directives/ng_for';
import * as import46 from '../../../../../src/app/common/selectdirective';
import * as import47 from '@angular/forms/src/directives/reactive_directives/form_group_name';
import * as import48 from '@angular/forms/src/directives/control_container';
import * as import49 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
export class Wrapper_ReceptionAwarenessAgentComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ReceptionAwarenessAgentComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this._changed = false;
    this.context = new import0.ReceptionAwarenessAgentComponent(p0,p1,p2,p3,p4,p5);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ReceptionAwarenessAgentComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ReceptionAwarenessAgentComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ReceptionAwarenessAgentComponent>;
  _ReceptionAwarenessAgentComponent_0_3:Wrapper_ReceptionAwarenessAgentComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ReceptionAwarenessAgentComponent_Host0,renderType_ReceptionAwarenessAgentComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'as4-receptionawareness-agent',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ReceptionAwarenessAgentComponent0(this.viewUtils,this,0,this._el_0);
    this._ReceptionAwarenessAgentComponent_0_3 = new Wrapper_ReceptionAwarenessAgentComponent(this.injectorGet(import8.FormBuilder,this.parentIndex),this.injectorGet(import9.SettingsStore,this.parentIndex),this.injectorGet(import10.SettingsService,this.parentIndex),this.injectorGet(import11.RuntimeService,this.parentIndex),this.injectorGet(import12.RuntimeStore,this.parentIndex),this.injectorGet(import13.DialogService,this.parentIndex));
    this.compView_0.create(this._ReceptionAwarenessAgentComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ReceptionAwarenessAgentComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ReceptionAwarenessAgentComponent) && (0 === requestNodeIndex))) { return this._ReceptionAwarenessAgentComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ReceptionAwarenessAgentComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._ReceptionAwarenessAgentComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ReceptionAwarenessAgentComponentNgFactory:import7.ComponentFactory<import0.ReceptionAwarenessAgentComponent> = new import7.ComponentFactory<import0.ReceptionAwarenessAgentComponent>('as4-receptionawareness-agent',View_ReceptionAwarenessAgentComponent_Host0,import0.ReceptionAwarenessAgentComponent);
const styles_ReceptionAwarenessAgentComponent:any[] = ([] as any[]);
class View_ReceptionAwarenessAgentComponent1 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import14.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_0_4:import15.Wrapper_NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_ReceptionAwarenessAgentComponent1,renderType_ReceptionAwarenessAgentComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import17.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_0_3 = new import14.Wrapper_NgSelectOption(new import18.ElementRef(this._el_0),this.renderer,(<View_ReceptionAwarenessAgentComponent0>this.parentView)._SelectControlValueAccessor_33_4.context);
    this._NgSelectMultipleOption_0_4 = new import15.Wrapper_NgSelectMultipleOption(new import18.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3.context; }
    if (((token === import20.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.$implicit.technicalName;
    this._NgSelectOption_0_3.check_value(currVal_0_0_0,throwOnChange,false);
    this._NgSelectOption_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = this.context.$implicit.technicalName;
    this._NgSelectMultipleOption_0_4.check_value(currVal_0_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_4:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_ReceptionAwarenessAgentComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_ReceptionAwarenessAgentComponent,{});
export class View_ReceptionAwarenessAgentComponent0 extends import1.AppView<import0.ReceptionAwarenessAgentComponent> {
  _el_0:any;
  _FormGroupDirective_0_3:import21.Wrapper_FormGroupDirective;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import22.Wrapper_NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import23.BoxComponent>;
  _BoxComponent_2_3:import24.Wrapper_BoxComponent;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  compView_9:import1.AppView<import25.InputComponent>;
  _InputComponent_9_3:import26.Wrapper_InputComponent;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _TextDirective_13_3:import27.Wrapper_TextDirective;
  _DefaultValueAccessor_13_4:import28.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_13_5:any[];
  _FormControlName_13_6:import29.Wrapper_FormControlName;
  _NgControl_13_7:any;
  _NgControlStatus_13_8:import22.Wrapper_NgControlStatus;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _FormGroupName_29_3:import30.Wrapper_FormGroupName;
  _ControlContainer_29_4:any;
  _NgControlStatusGroup_29_5:import22.Wrapper_NgControlStatusGroup;
  _text_30:any;
  _el_31:any;
  compView_31:import1.AppView<import25.InputComponent>;
  _InputComponent_31_3:import26.Wrapper_InputComponent;
  _text_32:any;
  _el_33:any;
  _SelectDirective_33_3:import31.Wrapper_SelectDirective;
  _SelectControlValueAccessor_33_4:import14.Wrapper_SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_33_5:any[];
  _FormControlName_33_6:import29.Wrapper_FormControlName;
  _NgControl_33_7:any;
  _NgControlStatus_33_8:import22.Wrapper_NgControlStatus;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _vc_35:import16.ViewContainer;
  _TemplateRef_35_5:any;
  _NgFor_35_6:import32.Wrapper_NgFor;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  compView_42:import1.AppView<import23.BoxComponent>;
  _BoxComponent_42_3:import24.Wrapper_BoxComponent;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  compView_46:import1.AppView<import33.ReceiverComponent>;
  _ReceiverComponent_46_3:import34.Wrapper_ReceiverComponent;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  compView_50:import1.AppView<import23.BoxComponent>;
  _BoxComponent_50_3:import24.Wrapper_BoxComponent;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  compView_54:import1.AppView<import35.StepSettingsComponent>;
  _StepSettingsComponent_54_3:import36.Wrapper_StepSettingsComponent;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  /*private*/ _expr_93:any;
  /*private*/ _expr_94:any;
  /*private*/ _expr_95:any;
  /*private*/ _expr_96:any;
  /*private*/ _expr_97:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ReceptionAwarenessAgentComponent0,renderType_ReceptionAwarenessAgentComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_93 = import17.UNINITIALIZED;
    this._expr_94 = import17.UNINITIALIZED;
    this._expr_95 = import17.UNINITIALIZED;
    this._expr_96 = import17.UNINITIALIZED;
    this._expr_97 = import17.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'form',new import3.InlineArray2(2,'class','form-horizontal'),(null as any));
    this._FormGroupDirective_0_3 = new import21.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_0_4 = this._FormGroupDirective_0_3.context;
    this._NgControlStatusGroup_0_5 = new import22.Wrapper_NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'as4-box',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import24.View_BoxComponent0(this.viewUtils,this,2,this._el_2);
    this._BoxComponent_2_3 = new import24.Wrapper_BoxComponent(new import18.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray8(6,'action','','class','btn btn-box-tool','type','button'),(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_4,'i',new import3.InlineArray2(2,'class','fa fa-save'),(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray4(4,'class','col-md-6 col-xs-12','content',''),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'as4-input',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_9 = new import26.View_InputComponent0(this.viewUtils,this,9,this._el_9);
    this._InputComponent_9_3 = new import26.Wrapper_InputComponent(this.parentView.injectorGet(import12.RuntimeStore,this.parentIndex));
    this._text_10 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','input-group'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n                    ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'input',new import3.InlineArray8(6,'class','form-control','formControlName','name','type','text'),(null as any));
    this._TextDirective_13_3 = new import27.Wrapper_TextDirective(new import18.ElementRef(this._el_13),this.renderer);
    this._DefaultValueAccessor_13_4 = new import28.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_13));
    this._NG_VALUE_ACCESSOR_13_5 = [this._DefaultValueAccessor_13_4.context];
    this._FormControlName_13_6 = new import29.Wrapper_FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_13_5);
    this._NgControl_13_7 = this._FormControlName_13_6.context;
    this._NgControlStatus_13_8 = new import22.Wrapper_NgControlStatus(this._NgControl_13_7);
    this._text_14 = this.renderer.createText(this._el_11,'\n                    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','input-group-btn'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'button',new import3.InlineArray4(4,'class','btn btn-flat','type','button'),(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_17,'i',new import3.InlineArray2(2,'class','fa fa-save'),(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_15,'button',new import3.InlineArray4(4,'class','btn btn-flat','type','button'),(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_20,'i',new import3.InlineArray2(2,'class','fa fa-undo'),(null as any));
    this._text_22 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_15,'button',new import3.InlineArray4(4,'class','btn btn-flat','type','button'),(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_23,'i',new import3.InlineArray2(2,'class','fa fa-trash-o'),(null as any));
    this._text_25 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n            ',(null as any));
    this.compView_9.create(this._InputComponent_9_3.context);
    this._text_28 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'formGroupName','transformer'),(null as any));
    this._FormGroupName_29_3 = new import30.Wrapper_FormGroupName(this._ControlContainer_0_4,(null as any),(null as any));
    this._ControlContainer_29_4 = this._FormGroupName_29_3.context;
    this._NgControlStatusGroup_29_5 = new import22.Wrapper_NgControlStatusGroup(this._ControlContainer_29_4);
    this._text_30 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'as4-input',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_31 = new import26.View_InputComponent0(this.viewUtils,this,31,this._el_31);
    this._InputComponent_31_3 = new import26.Wrapper_InputComponent(this.parentView.injectorGet(import12.RuntimeStore,this.parentIndex));
    this._text_32 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,(null as any),'select',new import3.InlineArray4(4,'class','form-control','formControlName','type'),(null as any));
    this._SelectDirective_33_3 = new import31.Wrapper_SelectDirective(new import18.ElementRef(this._el_33),this.renderer);
    this._SelectControlValueAccessor_33_4 = new import14.Wrapper_SelectControlValueAccessor(this.renderer,new import18.ElementRef(this._el_33));
    this._NG_VALUE_ACCESSOR_33_5 = [this._SelectControlValueAccessor_33_4.context];
    this._FormControlName_33_6 = new import29.Wrapper_FormControlName(this._ControlContainer_29_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_33_5);
    this._NgControl_33_7 = this._FormControlName_33_6.context;
    this._NgControlStatus_33_8 = new import22.Wrapper_NgControlStatus(this._NgControl_33_7);
    this._text_34 = this.renderer.createText(this._el_33,'\n                        ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_33,(null as any));
    this._vc_35 = new import16.ViewContainer(35,33,this,this._anchor_35);
    this._TemplateRef_35_5 = new import37.TemplateRef_(this,35,this._anchor_35);
    this._NgFor_35_6 = new import32.Wrapper_NgFor(this._vc_35.vcRef,this._TemplateRef_35_5,this.parentView.injectorGet(import38.IterableDiffers,this.parentIndex),this.ref);
    this._text_36 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n                ',(null as any));
    this.compView_31.create(this._InputComponent_31_3.context);
    this._text_38 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._text_39 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_2.create(this._BoxComponent_2_3.context);
    this._text_41 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_0,'as4-box',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_42 = new import24.View_BoxComponent0(this.viewUtils,this,42,this._el_42);
    this._BoxComponent_42_3 = new import24.Wrapper_BoxComponent(new import18.ElementRef(this._el_42),this.renderer);
    this._text_43 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray4(4,'class','col-md-6','content',''),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_44,'as4-receiver',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_46 = new import34.View_ReceiverComponent0(this.viewUtils,this,46,this._el_46);
    this._ReceiverComponent_46_3 = new import34.Wrapper_ReceiverComponent(this.parentView.injectorGet(import12.RuntimeStore,this.parentIndex),this.parentView.injectorGet(import8.FormBuilder,this.parentIndex));
    this.compView_46.create(this._ReceiverComponent_46_3.context);
    this._text_47 = this.renderer.createText(this._el_44,'\n        ',(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_42.create(this._BoxComponent_42_3.context);
    this._text_49 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_0,'as4-box',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_50 = new import24.View_BoxComponent0(this.viewUtils,this,50,this._el_50);
    this._BoxComponent_50_3 = new import24.Wrapper_BoxComponent(new import18.ElementRef(this._el_50),this.renderer);
    this._text_51 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray4(4,'class','col-md-6','content',''),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'\n            ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_52,'as4-step-settings',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_54 = new import36.View_StepSettingsComponent0(this.viewUtils,this,54,this._el_54);
    this._StepSettingsComponent_54_3 = new import36.Wrapper_StepSettingsComponent(this.parentView.injectorGet(import8.FormBuilder,this.parentIndex),this.parentView.injectorGet(import12.RuntimeStore,this.parentIndex),this.parentView.injectorGet(import13.DialogService,this.parentIndex));
    this.compView_54.create(this._StepSettingsComponent_54_3.context);
    this._text_55 = this.renderer.createText(this._el_52,'\n        ',(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_50.create(this._BoxComponent_50_3.context);
    this._text_57 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_0));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_13,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_13));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_17,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_17));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_20));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_23));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_33,new import3.InlineArray4(4,'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_33));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import39.TextDirective) && (13 === requestNodeIndex))) { return this._TextDirective_13_3.context; }
    if (((token === import40.DefaultValueAccessor) && (13 === requestNodeIndex))) { return this._DefaultValueAccessor_13_4.context; }
    if (((token === import41.NG_VALUE_ACCESSOR) && (13 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_13_5; }
    if (((token === import42.FormControlName) && (13 === requestNodeIndex))) { return this._FormControlName_13_6.context; }
    if (((token === import43.NgControl) && (13 === requestNodeIndex))) { return this._NgControl_13_7; }
    if (((token === import44.NgControlStatus) && (13 === requestNodeIndex))) { return this._NgControlStatus_13_8.context; }
    if (((token === import25.InputComponent) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._InputComponent_9_3.context; }
    if (((token === import37.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import45.NgFor) && (35 === requestNodeIndex))) { return this._NgFor_35_6.context; }
    if (((token === import46.SelectDirective) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._SelectDirective_33_3.context; }
    if (((token === import19.SelectControlValueAccessor) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._SelectControlValueAccessor_33_4.context; }
    if (((token === import41.NG_VALUE_ACCESSOR) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._NG_VALUE_ACCESSOR_33_5; }
    if (((token === import42.FormControlName) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._FormControlName_33_6.context; }
    if (((token === import43.NgControl) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._NgControl_33_7; }
    if (((token === import44.NgControlStatus) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._NgControlStatus_33_8.context; }
    if (((token === import25.InputComponent) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._InputComponent_31_3.context; }
    if (((token === import47.FormGroupName) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._FormGroupName_29_3.context; }
    if (((token === import48.ControlContainer) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._ControlContainer_29_4; }
    if (((token === import44.NgControlStatusGroup) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgControlStatusGroup_29_5.context; }
    if (((token === import23.BoxComponent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._BoxComponent_2_3.context; }
    if (((token === import33.ReceiverComponent) && (46 === requestNodeIndex))) { return this._ReceiverComponent_46_3.context; }
    if (((token === import23.BoxComponent) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._BoxComponent_42_3.context; }
    if (((token === import35.StepSettingsComponent) && (54 === requestNodeIndex))) { return this._StepSettingsComponent_54_3.context; }
    if (((token === import23.BoxComponent) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._BoxComponent_50_3.context; }
    if (((token === import49.FormGroupDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._FormGroupDirective_0_3.context; }
    if (((token === import48.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._ControlContainer_0_4; }
    if (((token === import44.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._NgControlStatusGroup_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.form;
    this._FormGroupDirective_0_3.check_form(currVal_0_0_0,throwOnChange,false);
    this._FormGroupDirective_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatusGroup_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = false;
    this._BoxComponent_2_3.check_collapsed(currVal_2_0_0,throwOnChange,false);
    if (this._BoxComponent_2_3.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    const currVal_9_0_0:any = 'Name';
    this._InputComponent_9_3.check_label(currVal_9_0_0,throwOnChange,false);
    if (this._InputComponent_9_3.ngDoCheck(this,this._el_9,throwOnChange)) { this.compView_9.markAsCheckOnce(); }
    this._TextDirective_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    this._DefaultValueAccessor_13_4.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_13_2_0:any = 'name';
    this._FormControlName_13_6.check_name(currVal_13_2_0,throwOnChange,false);
    this._FormControlName_13_6.ngDoCheck(this,this._el_13,throwOnChange);
    this._NgControlStatus_13_8.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_29_0_0:any = 'transformer';
    this._FormGroupName_29_3.check_name(currVal_29_0_0,throwOnChange,false);
    this._FormGroupName_29_3.ngDoCheck(this,this._el_29,throwOnChange);
    this._NgControlStatusGroup_29_5.ngDoCheck(this,this._el_29,throwOnChange);
    const currVal_31_0_0:any = 'Transformer';
    this._InputComponent_31_3.check_label(currVal_31_0_0,throwOnChange,false);
    if (this._InputComponent_31_3.ngDoCheck(this,this._el_31,throwOnChange)) { this.compView_31.markAsCheckOnce(); }
    this._SelectDirective_33_3.ngDoCheck(this,this._el_33,throwOnChange);
    this._SelectControlValueAccessor_33_4.ngDoCheck(this,this._el_33,throwOnChange);
    const currVal_33_2_0:any = 'type';
    this._FormControlName_33_6.check_name(currVal_33_2_0,throwOnChange,false);
    this._FormControlName_33_6.ngDoCheck(this,this._el_33,throwOnChange);
    this._NgControlStatus_33_8.ngDoCheck(this,this._el_33,throwOnChange);
    const currVal_35_0_0:any = this.context.transformers;
    this._NgFor_35_6.check_ngForOf(currVal_35_0_0,throwOnChange,false);
    this._NgFor_35_6.ngDoCheck(this,this._anchor_35,throwOnChange);
    const currVal_42_0_0:any = 'Receiver';
    this._BoxComponent_42_3.check_title(currVal_42_0_0,throwOnChange,false);
    const currVal_42_0_1:any = false;
    this._BoxComponent_42_3.check_collapsed(currVal_42_0_1,throwOnChange,false);
    if (this._BoxComponent_42_3.ngDoCheck(this,this._el_42,throwOnChange)) { this.compView_42.markAsCheckOnce(); }
    const currVal_46_0_0:any = this.context.form.get('receiver');
    this._ReceiverComponent_46_3.check_group(currVal_46_0_0,throwOnChange,false);
    this._ReceiverComponent_46_3.ngDoCheck(this,this._el_46,throwOnChange);
    const currVal_50_0_0:any = 'Steps';
    this._BoxComponent_50_3.check_title(currVal_50_0_0,throwOnChange,false);
    const currVal_50_0_1:any = false;
    this._BoxComponent_50_3.check_collapsed(currVal_50_0_1,throwOnChange,false);
    if (this._BoxComponent_50_3.ngDoCheck(this,this._el_50,throwOnChange)) { this.compView_50.markAsCheckOnce(); }
    const currVal_54_0_0:any = this.context.form.get('steps');
    this._StepSettingsComponent_54_3.check_group(currVal_54_0_0,throwOnChange,false);
    this._StepSettingsComponent_54_3.ngDoCheck(this,this._el_54,throwOnChange);
    this._vc_35.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_0_5.checkHost(this,this,this._el_0,throwOnChange);
    this._NgControlStatus_13_8.checkHost(this,this,this._el_13,throwOnChange);
    const currVal_93:any = this.context.form.dirty;
    if (import3.checkBinding(throwOnChange,this._expr_93,currVal_93)) {
      this.renderer.setElementClass(this._el_17,'btn-primary',currVal_93);
      this._expr_93 = currVal_93;
    }
    const currVal_94:boolean = !this.context.form.dirty;
    if (import3.checkBinding(throwOnChange,this._expr_94,currVal_94)) {
      this.renderer.setElementProperty(this._el_17,'disabled',currVal_94);
      this._expr_94 = currVal_94;
    }
    const currVal_95:any = this.context.form.dirty;
    if (import3.checkBinding(throwOnChange,this._expr_95,currVal_95)) {
      this.renderer.setElementClass(this._el_20,'btn-primary',currVal_95);
      this._expr_95 = currVal_95;
    }
    const currVal_96:boolean = !this.context.form.dirty;
    if (import3.checkBinding(throwOnChange,this._expr_96,currVal_96)) {
      this.renderer.setElementProperty(this._el_20,'disabled',currVal_96);
      this._expr_96 = currVal_96;
    }
    const currVal_97:any = this.context.isNew;
    if (import3.checkBinding(throwOnChange,this._expr_97,currVal_97)) {
      this.renderer.setElementProperty(this._el_23,'disabled',currVal_97);
      this._expr_97 = currVal_97;
    }
    this._NgControlStatusGroup_29_5.checkHost(this,this,this._el_29,throwOnChange);
    this._NgControlStatus_33_8.checkHost(this,this,this._el_33,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_9.internalDetectChanges(throwOnChange);
    this.compView_31.internalDetectChanges(throwOnChange);
    this.compView_42.internalDetectChanges(throwOnChange);
    this.compView_46.internalDetectChanges(throwOnChange);
    this.compView_50.internalDetectChanges(throwOnChange);
    this.compView_54.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_35.destroyNestedViews();
    this.compView_2.destroy();
    this.compView_9.destroy();
    this.compView_31.destroy();
    this.compView_42.destroy();
    this.compView_46.destroy();
    this.compView_50.destroy();
    this.compView_54.destroy();
    this._FormControlName_13_6.ngOnDestroy();
    this._FormControlName_33_6.ngOnDestroy();
    this._FormGroupName_29_3.ngOnDestroy();
    this._ReceiverComponent_46_3.ngOnDestroy();
    this._StepSettingsComponent_54_3.ngOnDestroy();
    this._FormGroupDirective_0_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) { cb(this._el_4,ctx); }
    if (((nodeIndex == 2) && (ngContentIndex == 1))) { cb(this._el_7,ctx); }
    if (((nodeIndex == 9) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 9) && (ngContentIndex == 1))) {
      cb(this._text_10,ctx);
      cb(this._el_11,ctx);
      cb(this._text_27,ctx);
    }
    if (((nodeIndex == 31) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 31) && (ngContentIndex == 1))) {
      cb(this._text_32,ctx);
      cb(this._el_33,ctx);
      cb(this._text_37,ctx);
    }
    if (((nodeIndex == 42) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 42) && (ngContentIndex == 1))) { cb(this._el_44,ctx); }
    if (((nodeIndex == 50) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 50) && (ngContentIndex == 1))) { cb(this._el_52,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 35)) { return new View_ReceptionAwarenessAgentComponent1(this.viewUtils,this,35,this._anchor_35,this._vc_35); }
    return (null as any);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_13(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_13_4.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_17(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.save()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.reset()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.delete()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_33(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_33_4.handleEvent(eventName,$event) && result);
    return result;
  }
}