/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../src/app/monitor/filter/filter.component';
import * as i2 from '../../../../../src/app/monitor/service.token';
import * as i3 from '@angular/router';
const styles_FilterComponent:any[] = ([] as any[]);
export const RenderType_FilterComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_FilterComponent,data:{}});
export function View_FilterComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n    '])),i0.ɵncd((null as any),
      0),(_l()(),i0.ɵted(-1,(null as any),['\n\n']))],(null as any),(null as any));
}
export function View_FilterComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'as4-filter',
      ([] as any[]),(null as any),(null as any),(null as any),View_FilterComponent_0,
      RenderType_FilterComponent)),i0.ɵdid(1,245760,(null as any),0,i1.FilterComponent,
      [i2.MESSAGESERVICETOKEN,i3.ActivatedRoute,i3.Router],(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export const FilterComponentNgFactory:i0.ComponentFactory<i1.FilterComponent> = i0.ɵccf('as4-filter',
    i1.FilterComponent,View_FilterComponent_Host_0,{filter:'filter'},{outFilter:'outFilter',
        onSearch:'onSearch',onFiltersLoaded:'onFiltersLoaded'},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvZmlsdGVyL2ZpbHRlci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvZmlsdGVyL2ZpbHRlci5jb21wb25lbnQudHMiLCJuZzovLy9DOi9EZXYvY29kaXQudmlzdWFsc3R1ZGlvLmNvbS9BUzQuTkVUL3NvdXJjZS9GZS9FdS5FRGVsaXZlcnkuQVM0LkZlL3VpL3NyYy9hcHAvbW9uaXRvci9maWx0ZXIvZmlsdGVyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvZmlsdGVyL2ZpbHRlci5jb21wb25lbnQudHMuRmlsdGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPCEtLSA8Zm9ybSAobmdTdWJtaXQpPVwic2VhcmNoKHRydWUpXCIgY2xhc3M9XCJmb3JtLWhvcml6b250YWxcIiAjZm9ybT1cIm5nRm9ybVwiPiAtLT5cclxuICAgIDxuZy1jb250ZW50PjwvbmctY29udGVudD5cclxuXHJcbjwhLS0gPC9mb3JtPiAtLT4iLCI8YXM0LWZpbHRlcj48L2FzNC1maWx0ZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNBZ0YscURBQzVFO01BQUEsR0FBeUI7OztvQkNEN0I7TUFBQTtnQ0FBQSxVQUFBO01BQUE7O1FBQUE7Ozs7OyJ9
