/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.panel[_ngcontent-%COMP%]{margin-top:10px;padding-top:10px;padding-bottom:10px;border-bottom:1px solid #cccc;box-shadow:5px 5px 5px #ccc;padding:10px}.truncate[_ngcontent-%COMP%]{width:200px}.truncate[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]{display:block;width:200px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL3NldHRpbmdzL3NtcGNvbmZpZ3VyYXRpb24vc21wY29uZmlndXJhdGlvbi5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9EZXYvY29kaXQudmlzdWFsc3R1ZGlvLmNvbS9BUzQuTkVUL3NvdXJjZS9GZS9FdS5FRGVsaXZlcnkuQVM0LkZlL3VpL3NyYy9hcHAvc2V0dGluZ3Mvc21wY29uZmlndXJhdGlvbi9zbXBjb25maWd1cmF0aW9uLmNvbXBvbmVudC5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
