/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../common/box/box.component.ngfactory';
import * as i2 from '../../../../../src/app/common/box/box.component';
import * as i3 from '../../common/clipboard/clipboard.component.ngfactory';
import * as i4 from '../../../../../src/app/common/clipboard/clipboard.component';
import * as i5 from '../../../../../src/app/monitor/exceptiondetail/exceptiondetail.component';
import * as i6 from '@angular/router';
import * as i7 from '../../../../../src/app/monitor/exception/exception.service';
const styles_ExceptionDetailComponent:any[] = ([] as any[]);
export const RenderType_ExceptionDetailComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ExceptionDetailComponent,data:{}});
export function View_ExceptionDetailComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),8,'as4-box',([] as any[]),
      (null as any),(null as any),(null as any),i1.View_BoxComponent_0,i1.RenderType_BoxComponent)),
      i0.ɵdid(1,114688,(null as any),0,i2.BoxComponent,[i0.ElementRef,i0.Renderer],
          {showTitle:[0,'showTitle']},(null as any)),(_l()(),i0.ɵted(-1,2,['\n    '])),
      (_l()(),i0.ɵeld(3,0,(null as any),1,1,'as4-clipboard',([] as any[]),(null as any),
          (null as any),(null as any),i3.View_ClipboardComponent_0,i3.RenderType_ClipboardComponent)),
      i0.ɵdid(4,49152,(null as any),0,i4.ClipboardComponent,([] as any[]),{content:[0,
          'content']},(null as any)),(_l()(),i0.ɵted(-1,2,['\n    '])),(_l()(),i0.ɵeld(6,
          0,(null as any),2,1,'p',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted(7,(null as any),['',''])),
      (_l()(),i0.ɵted(-1,2,['\n']))],(_ck,_v) => {
    var _co:i5.ExceptionDetailComponent = _v.component;
    const currVal_0:any = false;
    _ck(_v,1,0,currVal_0);
    const currVal_1:any = _co.data;
    _ck(_v,4,0,currVal_1);
  },(_ck,_v) => {
    var _co:i5.ExceptionDetailComponent = _v.component;
    const currVal_2:any = _co.data;
    _ck(_v,7,0,currVal_2);
  });
}
export function View_ExceptionDetailComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'as4-exceptiondetail',
      ([] as any[]),(null as any),(null as any),(null as any),View_ExceptionDetailComponent_0,
      RenderType_ExceptionDetailComponent)),i0.ɵdid(1,49152,(null as any),0,i5.ExceptionDetailComponent,
      [i6.ActivatedRoute,i7.ExceptionService],(null as any),(null as any))],(null as any),
      (null as any));
}
export const ExceptionDetailComponentNgFactory:i0.ComponentFactory<i5.ExceptionDetailComponent> = i0.ɵccf('as4-exceptiondetail',
    i5.ExceptionDetailComponent,View_ExceptionDetailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvZXhjZXB0aW9uZGV0YWlsL2V4Y2VwdGlvbmRldGFpbC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvZXhjZXB0aW9uZGV0YWlsL2V4Y2VwdGlvbmRldGFpbC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9EZXYvY29kaXQudmlzdWFsc3R1ZGlvLmNvbS9BUzQuTkVUL3NvdXJjZS9GZS9FdS5FRGVsaXZlcnkuQVM0LkZlL3VpL3NyYy9hcHAvbW9uaXRvci9leGNlcHRpb25kZXRhaWwvZXhjZXB0aW9uZGV0YWlsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL21vbml0b3IvZXhjZXB0aW9uZGV0YWlsL2V4Y2VwdGlvbmRldGFpbC5jb21wb25lbnQudHMuRXhjZXB0aW9uRGV0YWlsQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFzNC1ib3ggW3Nob3dUaXRsZV09XCJmYWxzZVwiPlxyXG4gICAgPGFzNC1jbGlwYm9hcmQgW2NvbnRlbnRdPVwiZGF0YVwiPjwvYXM0LWNsaXBib2FyZD5cclxuICAgIDxwPnt7ZGF0YX19PC9wPlxyXG48L2FzNC1ib3g+IiwiPGFzNC1leGNlcHRpb25kZXRhaWw+PC9hczQtZXhjZXB0aW9uZGV0YWlsPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7YUFBQTtVQUFBLDJDQUE2QjtNQUN6QjtVQUFBO2FBQUE7VUFBQSwyQkFBZ0Qsa0NBQ2hEO1VBQUE7VUFBQSw4QkFBRztNQUFZOztJQUZWO0lBQVQsV0FBUyxTQUFUO0lBQ21CO0lBQWYsV0FBZSxTQUFmOzs7SUFDRztJQUFBOzs7O29CQ0ZQO01BQUE7eUNBQUEsVUFBQTtNQUFBOzs7OyJ9
