/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/authentication/authentication.module';
import * as i2 from './login/login.component.ngfactory';
import * as i3 from './unauthorized/unauthorized.component.ngfactory';
import * as i4 from '@angular/forms';
import * as i5 from 'angular2-jwt/angular2-jwt';
import * as i6 from '../../../../src/app/authentication/authentication.store';
import * as i7 from '../../../../src/app/authentication/logout.service';
import * as i8 from '@angular/router';
import * as i9 from '../../../../src/app/authentication/authentication.service';
import * as i10 from '@angular/http';
import * as i11 from '../../../../src/app/common/spinner/spinner.service';
import * as i12 from '../../../../src/app/common/dialog.service';
import * as i13 from '../../../../src/app/setup/setup.guard';
import * as i14 from '../../../../src/app/setup/setup.service';
import * as i15 from '../../../../src/app/authentication/login/login.component';
import * as i16 from '../../../../src/app/authentication/unauthorized/unauthorized.component';
export const AuthenticationModuleNgFactory:i0.NgModuleFactory<i1.AuthenticationModule> = i0.ɵcmf(i1.AuthenticationModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.LoginComponentNgFactory,i3.UnauthorizedComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(4608,
          i4.FormBuilder,i4.FormBuilder,([] as any[])),i0.ɵmpd(5120,i5.JwtHelper,i1.jwtHelperFactory,
          ([] as any[])),i0.ɵmpd(4608,i6.AuthenticationStore,i6.AuthenticationStore,
          [i5.JwtHelper]),i0.ɵmpd(4608,i7.LogoutService,i7.LogoutService,[i8.Router]),
          i0.ɵmpd(4608,i9.AuthenticationService,i9.AuthenticationService,[i10.Http,
              i6.AuthenticationStore,i8.Router,i11.SpinnerService,i12.DialogService,
              i7.LogoutService]),i0.ɵmpd(4608,i13.SetupGuard,i13.SetupGuard,[i14.SetupService,
              i8.Router]),i0.ɵmpd(512,i8.RouterModule,i8.RouterModule,[[2,i8.ɵa],[2,
              i8.Router]]),i0.ɵmpd(512,i4.ɵba,i4.ɵba,([] as any[])),i0.ɵmpd(512,i4.FormsModule,
              i4.FormsModule,([] as any[])),i0.ɵmpd(512,i4.ReactiveFormsModule,i4.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i1.AuthenticationModule,i1.AuthenticationModule,
              ([] as any[])),i0.ɵmpd(1024,i8.ROUTES,() => {
            return [[{path:'login',component:i15.LoginComponent,data:{isAuthCheck:false},
                canActivate:[i13.SetupGuard]},{path:'unauthorized',component:i16.UnauthorizedComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2L2NvZGl0LnZpc3VhbHN0dWRpby5jb20vQVM0Lk5FVC9zb3VyY2UvRmUvRXUuRURlbGl2ZXJ5LkFTNC5GZS91aS9zcmMvYXBwL2F1dGhlbnRpY2F0aW9uL2F1dGhlbnRpY2F0aW9uLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9EZXYvY29kaXQudmlzdWFsc3R1ZGlvLmNvbS9BUzQuTkVUL3NvdXJjZS9GZS9FdS5FRGVsaXZlcnkuQVM0LkZlL3VpL3NyYy9hcHAvYXV0aGVudGljYXRpb24vYXV0aGVudGljYXRpb24ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
